import { html } from "https://unpkg.com/htm/preact/standalone.module.js";
import musicListParent from "./musicList/musicListParent.js";
import addSongParent from "./addSong/addSongParent.js";
import pieChartParent from "./pieChart/pieChartParent.js";

//this collates and combines the elements generated by the sub components and prepares them to go to app.js
function Components() {
  return html` <${musicListParent} />
    <${addSongParent} />
    <${pieChartParent} />`;
}

export default Components;
